
// Dữ liệu cho phòng trọ
export const rooms = [
  {
    id: 1,
    name: "Phòng 101",
    address: "123 Nguyễn Văn A, Quận 1, TP.HCM",
    price: 2500000,
    area: 20,
    status: "available",
    landlordId: 1,
    images: ["/placeholder.svg"],
    facilities: ["Điều hòa", "Tủ lạnh", "Máy giặt", "Wifi"],
    description: "Phòng mới xây, sạch sẽ, đầy đủ tiện nghi, gần trung tâm.",
  },
  {
    id: 2,
    name: "Phòng 102",
    address: "456 Lê Văn B, Quận 2, TP.HCM",
    price: 3000000,
    area: 25,
    status: "rented",
    landlordId: 1,
    images: ["/placeholder.svg"],
    facilities: ["Điều hòa", "Tủ lạnh", "Tivi", "Wifi"],
    description: "Phòng rộng rãi, thoáng mát, view đẹp, gần siêu thị.",
  },
  {
    id: 3,
    name: "Phòng 201",
    address: "789 Trần Văn C, Quận 3, TP.HCM",
    price: 2800000,
    area: 22,
    status: "available",
    landlordId: 2,
    images: ["/placeholder.svg"],
    facilities: ["Điều hòa", "Giường", "Tủ quần áo", "Wifi"],
    description: "Phòng đẹp, an ninh tốt, gần trường học và chợ.",
  },
  {
    id: 4,
    name: "Phòng 202",
    address: "101 Phạm Văn D, Quận Bình Thạnh, TP.HCM",
    price: 3500000,
    area: 28,
    status: "maintenance",
    landlordId: 2,
    images: ["/placeholder.svg"],
    facilities: ["Điều hòa", "Tủ lạnh", "Máy giặt", "Wifi", "Tivi"],
    description: "Phòng cao cấp, nội thất mới, khu vực yên tĩnh.",
  },
  {
    id: 5,
    name: "Phòng 301",
    address: "202 Võ Văn E, Quận 4, TP.HCM",
    price: 2200000,
    area: 18,
    status: "available",
    landlordId: 3,
    images: ["/placeholder.svg"],
    facilities: ["Điều hòa", "Giường", "Tủ quần áo"],
    description: "Phòng giá rẻ, phù hợp sinh viên, gần trường đại học.",
  },
];

// Dữ liệu cho chủ cho thuê
export const landlords = [
  {
    id: 1,
    name: "Nguyễn Văn An",
    phone: "0901234567",
    email: "nguyenvanan@example.com",
    address: "123 Lê Lợi, Quận 1, TP.HCM",
    joinedDate: "2022-01-15",
    totalRooms: 5,
    avatar: "/placeholder.svg",
  },
  {
    id: 2,
    name: "Trần Thị Bình",
    phone: "0912345678",
    email: "tranthibinh@example.com",
    address: "456 Nguyễn Huệ, Quận 3, TP.HCM",
    joinedDate: "2022-03-20",
    totalRooms: 8,
    avatar: "/placeholder.svg",
  },
  {
    id: 3,
    name: "Lê Văn Cường",
    phone: "0923456789",
    email: "levancuong@example.com",
    address: "789 Lý Tự Trọng, Quận 5, TP.HCM",
    joinedDate: "2022-06-10",
    totalRooms: 3,
    avatar: "/placeholder.svg",
  },
  {
    id: 4,
    name: "Phạm Thị Dung",
    phone: "0934567890",
    email: "phamthidung@example.com",
    address: "101 Nam Kỳ Khởi Nghĩa, Quận 1, TP.HCM",
    joinedDate: "2022-08-05",
    totalRooms: 6,
    avatar: "/placeholder.svg",
  },
];

// Dữ liệu cho tin nhắn
export const conversations = [
  {
    id: 1,
    landlordId: 1,
    landlordName: "Nguyễn Văn An",
    landlordAvatar: "/placeholder.svg",
    unread: 2,
    lastMessage: "Xin chào, tôi muốn hỏi về phòng 101",
    lastMessageTime: "10:30",
    isOnline: true,
    messages: [
      {
        id: 1,
        senderId: "admin",
        text: "Chào anh An, có phòng 101 còn trống không ạ?",
        timestamp: "2023-04-15T10:25:00",
      },
      {
        id: 2,
        senderId: 1,
        text: "Chào bạn, phòng 101 hiện vẫn còn trống.",
        timestamp: "2023-04-15T10:26:00",
      },
      {
        id: 3,
        senderId: "admin",
        text: "Giá phòng là bao nhiêu vậy anh?",
        timestamp: "2023-04-15T10:27:00",
      },
      {
        id: 4,
        senderId: 1,
        text: "Phòng này giá 2.5 triệu/tháng, đã bao gồm điện nước cơ bản.",
        timestamp: "2023-04-15T10:28:00",
      },
      {
        id: 5,
        senderId: "admin",
        text: "Tôi có thể đến xem phòng vào chiều nay được không?",
        timestamp: "2023-04-15T10:29:00",
      },
      {
        id: 6,
        senderId: 1,
        text: "Xin chào, tôi muốn hỏi về phòng 101",
        timestamp: "2023-04-15T10:30:00",
      },
    ],
  },
  {
    id: 2,
    landlordId: 2,
    landlordName: "Trần Thị Bình",
    landlordAvatar: "/placeholder.svg",
    unread: 0,
    lastMessage: "Phòng 202 đã được sửa chữa xong",
    lastMessageTime: "Hôm qua",
    isOnline: false,
    messages: [
      {
        id: 1,
        senderId: "admin",
        text: "Chị Bình ơi, phòng 202 đang có vấn đề về điều hòa.",
        timestamp: "2023-04-14T14:10:00",
      },
      {
        id: 2,
        senderId: 2,
        text: "Chào bạn, tôi sẽ cho người đến sửa trong ngày hôm nay.",
        timestamp: "2023-04-14T14:15:00",
      },
      {
        id: 3,
        senderId: "admin",
        text: "Cảm ơn chị, vậy khoảng mấy giờ thợ sẽ đến ạ?",
        timestamp: "2023-04-14T14:20:00",
      },
      {
        id: 4,
        senderId: 2,
        text: "Dự kiến khoảng 3h chiều nhé.",
        timestamp: "2023-04-14T14:25:00",
      },
      {
        id: 5,
        senderId: 2,
        text: "Phòng 202 đã được sửa chữa xong",
        timestamp: "2023-04-14T17:30:00",
      },
    ],
  },
  {
    id: 3,
    landlordId: 3,
    landlordName: "Lê Văn Cường",
    landlordAvatar: "/placeholder.svg",
    unread: 1,
    lastMessage: "Tôi sẽ tăng giá phòng từ tháng sau",
    lastMessageTime: "Thứ 2",
    isOnline: true,
    messages: [
      {
        id: 1,
        senderId: 3,
        text: "Chào bạn, tôi dự định sẽ tăng giá phòng từ tháng sau.",
        timestamp: "2023-04-10T09:00:00",
      },
    ],
  },
];

export const recentActivities = [
  {
    id: 1,
    action: "Thêm mới",
    target: "Phòng 301",
    time: "10 phút trước",
    icon: "plus",
  },
  {
    id: 2,
    action: "Cập nhật",
    target: "Phòng 102",
    time: "30 phút trước",
    icon: "edit",
  },
  {
    id: 3,
    action: "Đã cho thuê",
    target: "Phòng 201",
    time: "2 giờ trước",
    icon: "check",
  },
  {
    id: 4,
    action: "Tin nhắn mới",
    target: "Nguyễn Văn An",
    time: "3 giờ trước",
    icon: "message-circle",
  },
  {
    id: 5,
    action: "Thêm mới",
    target: "Chủ trọ Phạm Thị Dung",
    time: "1 ngày trước",
    icon: "user",
  },
];

// Thống kê tổng quan
export const statistics = {
  totalRooms: 22,
  availableRooms: 12,
  rentedRooms: 8,
  maintenanceRooms: 2,
  totalLandlords: 4,
  totalRevenue: 25000000,
  occupancyRate: 36.4, // Tỷ lệ lấp đầy (8/22)
};
